# Generated by Django 4.0.6 on 2022-08-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='access_level',
            field=models.IntegerField(choices=[(1, 'Member'), (2, 'Admin')], default=1),
        ),
    ]
