# Generated by Django 4.0.6 on 2022-09-01 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectmembership_access_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='profile_picture',
        ),
    ]
