# Generated by Django 4.0.6 on 2022-10-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='project_profile_pics'),
        ),
    ]
