# Generated by Django 4.0.6 on 2022-10-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_rename_user_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='board',
            name='owner_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
