# Generated by Django 4.0.6 on 2022-10-27 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_board_color_board_image_url_item_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='labels',
            field=models.ManyToManyField(blank=True, to='boards.label'),
        ),
        migrations.AddField(
            model_name='label',
            name='board',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='boards.board'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='label',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
