# Generated by Django 4.0.6 on 2022-10-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_remove_label_item_item_labels_label_board_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='order',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='order',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
    ]
